@extends('layouts.app')
@section('title', 'Report: ' . $report->report_id)
@section('content')
<div class="max-w-4xl mx-auto">
    <div class="bg-white rounded-2xl shadow-sm border border-gray-100 p-6 mb-6">
        <div class="flex justify-between items-start mb-6">
            <div>
                <h2 class="text-xl font-bold">{{ $report->report_id }}</h2>
                <p class="text-gray-500">Generated: {{ $report->generated_at?->format('M d, Y h:i A') }}</p>
            </div>
            <div class="flex gap-2">
                <form action="{{ route('reports.regenerate', $report) }}" method="POST" class="inline">
                    @csrf
                    <button type="submit" onclick="return confirm('Regenerate this report with latest data?')" 
                            class="px-4 py-2 bg-gray-100 text-gray-700 rounded-xl hover:bg-gray-200 flex items-center gap-2">
                        <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15"></path>
                        </svg>
                        Regenerate
                    </button>
                </form>
                <a href="{{ route('reports.download', $report) }}" class="px-4 py-2 bg-primary-600 text-white rounded-xl hover:bg-primary-700 flex items-center gap-2">
                    <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"></path>
                    </svg>
                    Download PDF
                </a>
            </div>
        </div>

        <div class="grid grid-cols-2 gap-4 mb-6 p-4 bg-gray-50 rounded-xl">
            <div><span class="text-gray-500">Patient:</span> <strong>{{ $report->booking->patient->name }}</strong></div>
            <div><span class="text-gray-500">Patient ID:</span> {{ $report->booking->patient->patient_id }}</div>
            <div><span class="text-gray-500">Booking:</span> {{ $report->booking->booking_id }}</div>
            <div><span class="text-gray-500">Generated By:</span> {{ $report->generatedBy?->name ?? 'System' }}</div>
        </div>

        <h3 class="font-semibold mb-4">Test Results</h3>
        <table class="w-full">
            <thead class="bg-gray-50">
                <tr>
                    <th class="px-4 py-3 text-left text-xs font-semibold text-gray-500 uppercase">Test</th>
                    <th class="px-4 py-3 text-left text-xs font-semibold text-gray-500 uppercase">Result</th>
                    <th class="px-4 py-3 text-left text-xs font-semibold text-gray-500 uppercase">Normal Range</th>
                    <th class="px-4 py-3 text-left text-xs font-semibold text-gray-500 uppercase">Flag</th>
                </tr>
            </thead>
            <tbody class="divide-y">
                @foreach($report->booking->bookingTests as $bt)
                <tr>
                    <td class="px-4 py-3 font-medium">{{ $bt->test->name }}</td>
                    <td class="px-4 py-3 font-mono">{{ $bt->result?->value ?? '-' }} {{ $bt->test->unit }}</td>
                    <td class="px-4 py-3 text-sm text-gray-600">{{ $bt->test->normal_range }}</td>
                    <td class="px-4 py-3">
                        @if($bt->result?->flag && $bt->result->flag !== 'normal')
                        <span class="px-2 py-1 rounded text-xs font-bold {{ $bt->result->flag_badge }}">{{ strtoupper(str_replace('_', ' ', $bt->result->flag)) }}</span>
                        @else
                        <span class="text-green-600">Normal</span>
                        @endif
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>

    <a href="{{ route('reports.index') }}" class="text-primary-600 hover:underline">← Back to Reports</a>
</div>
@endsection
