<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Verify Report - PathLAS</title>
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body class="bg-gray-100 min-h-screen flex items-center justify-center p-6">
    <div class="max-w-md w-full bg-white rounded-2xl shadow-lg p-8 text-center">
        @if($valid)
        <div class="w-16 h-16 bg-green-100 rounded-full flex items-center justify-center mx-auto mb-4">
            <svg class="w-8 h-8 text-green-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7"></path>
            </svg>
        </div>
        <h1 class="text-2xl font-bold text-green-600 mb-2">Valid Report</h1>
        <p class="text-gray-600 mb-6">This report is authentic and was generated by PathLAS.</p>
        
        <div class="text-left bg-gray-50 rounded-xl p-4 mb-4">
            <p><span class="text-gray-500">Report ID:</span> <strong>{{ $report->report_id }}</strong></p>
            <p><span class="text-gray-500">Patient:</span> {{ $report->booking->patient->name }}</p>
            <p><span class="text-gray-500">Generated:</span> {{ $report->generated_at?->format('M d, Y h:i A') }}</p>
            <p><span class="text-gray-500">Generated By:</span> {{ $report->generatedBy?->name ?? 'System' }}</p>
        </div>
        @else
        <div class="w-16 h-16 bg-red-100 rounded-full flex items-center justify-center mx-auto mb-4">
            <svg class="w-8 h-8 text-red-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"></path>
            </svg>
        </div>
        <h1 class="text-2xl font-bold text-red-600 mb-2">Invalid Report</h1>
        <p class="text-gray-600">This report could not be verified. It may be invalid or does not exist in our system.</p>
        @endif
        
        <p class="text-sm text-gray-400 mt-6">PathLAS - Pathology Lab Automation System</p>
    </div>
</body>
</html>
